package com.gpunch.utils

import android.content.Context
import android.location.Location
import android.provider.Settings

/**
 * Client-side geofence utilities.
 * Uses Android's native distance calculation for client-side pre-validation.
 */
object GeofenceUtils {

    /**
     * Calculate distance in metres between two lat/lon pairs using Location.distanceBetween().
     */
    fun distanceBetween(lat1: Double, lon1: Double, lat2: Double, lon2: Double): Double {
        val results = FloatArray(1)
        Location.distanceBetween(lat1, lon1, lat2, lon2, results)
        return results[0].toDouble()
    }

    /**
     * Verify that the location was NOT generated by a mock/spoofing provider.
     * Checks:
     *  1. Location.isMock (API 18+, reliable on API 31+)
     *  2. Mock location developer option enabled
     */
    fun isMockLocation(context: Context, location: Location): Boolean {
        // Direct flag on the Location object (most reliable)
        if (location.isMock) return true

        // Developer option: "Allow mock locations" (deprecated but still works on older APIs)
        val mockSetting = Settings.Secure.getString(
            context.contentResolver,
            Settings.Secure.ALLOW_MOCK_LOCATION
        )
        return mockSetting == "1"
    }

    /**
     * Android ANDROID_ID – a 64-bit device identifier.
     * Note: resets on factory reset; unique per (app, device, signing key).
     */
    fun getAndroidId(context: Context): String =
        Settings.Secure.getString(context.contentResolver, Settings.Secure.ANDROID_ID) ?: "unknown"
}
