package com.gpunch.utils

import android.content.Context
import android.location.Location
import android.provider.Settings
import kotlin.math.*

/**
 * Client-side geofence utilities.
 * Mirrors the Haversine logic in the backend for pre-validation before API call.
 */
object GeofenceUtils {

    /**
     * Calculate distance in metres between two lat/lon pairs using the Haversine formula.
     * Equivalent to Android's Location.distanceBetween().
     */
    fun haversineDistance(lat1: Double, lon1: Double, lat2: Double, lon2: Double): Double {
        val R = 6_371_000.0
        val dLat = Math.toRadians(lat2 - lat1)
        val dLon = Math.toRadians(lon2 - lon1)
        val a = sin(dLat / 2).pow(2) +
                cos(Math.toRadians(lat1)) * cos(Math.toRadians(lat2)) *
                sin(dLon / 2).pow(2)
        val c = 2 * atan2(sqrt(a), sqrt(1 - a))
        return R * c
    }

    /**
     * Verify that the location was NOT generated by a mock/spoofing provider.
     * Checks:
     *  1. Location.isMock (API 18+, reliable on API 31+)
     *  2. Mock location developer option enabled
     */
    fun isMockLocation(context: Context, location: Location): Boolean {
        // Direct flag on the Location object (most reliable)
        if (location.isMock) return true

        // Developer option: "Allow mock locations" (deprecated but still works on older APIs)
        val mockSetting = Settings.Secure.getString(
            context.contentResolver,
            Settings.Secure.ALLOW_MOCK_LOCATION
        )
        return mockSetting == "1"
    }

    /**
     * Android ANDROID_ID – a 64-bit device identifier.
     * Note: resets on factory reset; unique per (app, device, signing key).
     */
    fun getAndroidId(context: Context): String =
        Settings.Secure.getString(context.contentResolver, Settings.Secure.ANDROID_ID) ?: "unknown"
}
